### ISSUE TITLE
Users'Feedback

### ISSUE THREAD

**Issue by PHPISTHEBESTLANGUAGE** [hehelego/oops-EFonline#1]
隐私窗口和全自动程序会导致遇见一个BUG
       EF页面要求有一次''麦克风测试''并阻止了包括且不限于的页面跳转和鼠标操作,可是程序此时跳过了这个''麦克风测试'',导致了页面中止操作并卡死.此BUG适用于fuckEF.py bf9d5fa 

还有一件事,cmd里的clear是cls.

**Comment by hehelego** [comment]
我暂时没有遇到过这个bug.   
在非隐私模式下能否复现?  

f

**Comment by teafrogsf-colldisSavior** [comment]
经本地测试，程序会跳过这个测试，同时发送通过的请求。

**Comment by hehelego** [comment]
缺少进一步反馈,开发者暂时无法复现,暂时关闭掉该issue.
