### ISSUE TITLE
Bugs that cause it unable to move forward

### ISSUE THREAD

**Issue by GuiltyInnocence** [hehelego/oops-EFonline#5]
1. On some occasions (it is unable to figure out exactly what kind) the script will wrongly skip to next unit(a.k.a.单元) while the previous unit has not been finished yet.
2. On some occasions (it is still unable to figure out exactly what kind, lol) the script did "finished" all the lesson(a.k.a.课程) of a unit, but it was unable to move forward to the next unit. One of the lesson prompts that `你还需通过-2组课程`.

Environment: python 3.9.2 firefox 86.0-2 geckodriver 0.26.1-1 all from Archlinux pacman repo
Since there is no log from the script, I didn't get any debug information.

**Comment by GuiltyInnocence** [comment]
For the first problem I guess it is caused by the async loading of javascript along with the terrible network of Shanghaitech.
:(

**Comment by hehelego** [comment]
Sorry, contact @teafrogsf-colldisSavior please,  
I have never reviewed the fully-automation part, and can't provide any help.

**Comment by resplendent-star** [comment]
> 对于第一个问题，我想这是由于javascript的异步加载以及Shanghaitech的糟糕网络引起的。
> :(

shanghaitech HHHHHHHHHHH!!!!!!!!!!!!!!!!!!!!!!!!小伙子咱能交流一下么

**Comment by hehelego** [comment]
Inactive, temporarily closed.
